import { schoolGames, TRICKY_ORDER } from './curriculum.js';
// Faith Craft Family Edition: leveled word banks and word-game builders (Pre-K to Grade 8).
// Levels: 0 = Pre-K, 1 = K, 2..9 = Grades 1..8. Pictures are emoji (drawn icons, no photos).
import { WL } from './phonics.js';
export function shuffle(a) { a = a.slice(); for (let i = a.length - 1; i > 0; i--) { const j = Math.random() * (i + 1) | 0; [a[i], a[j]] = [a[j], a[i]]; } return a; }
const pickN = (a, n) => shuffle(a).slice(0, n);

// ---------- Pictures ----------
export const PIC = {
  dog: '🐶', cat: '🐱', apple: '🍎', ball: '⚽', shoe: '👟', bird: '🐦', banana: '🍌', car: '🚗', fish: '🐟', moon: '🌙', tree: '🌳', house: '🏠', book: '📖', star: '⭐',
  carrot: '🥕', drum: '🥁', ladder: '🪜', turtle: '🐢', rabbit: '🐰', sheep: '🐑', camel: '🐫', bread: '🍞', rainbow: '🌈', boat: '⛵', basket: '🧺', candle: '🕯️',
  lion: '🦁', penguin: '🐧', mountain: '⛰️', bridge: '🌉', anchor: '⚓', feather: '🪶', shell: '🐚', crown: '👑', lamp: '🪔', key: '🔑', owl: '🦉', tent: '⛺',
  volcano: '🌋', cactus: '🌵', compass: '🧭', microscope: '🔬', telescope: '🔭', scroll: '📜', trumpet: '🎺', wheat: '🌾', dove: '🕊️', olive: '🫒', globe: '🌍', parachute: '🪂',
  hat: '🎩', bat: '🦇', cap: '🧢', map: '🗺️', van: '🚐', pig: '🐷', pin: '📌', lips: '👄', fox: '🦊', box: '📦', log: '🪵', sun: '☀️', bus: '🚌', nut: '🥜', bug: '🐛', bed: '🛏️', hen: '🐔', web: '🕸️', net: '🥅', ten: '🔟',
  bee: '🐝', cake: '🎂', snake: '🐍', king: '🤴', ring: '💍', spoon: '🥄', bear: '🐻', chair: '🪑', goat: '🐐', mouse: '🐭', clock: '🕐', sock: '🧦', nose: '👃', rose: '🌹', frog: '🐸', duck: '🦆',
  horse: '🐴', gift: '🎁', leaf: '🍃', lemon: '🍋', monkey: '🐵', pen: '🖊️', six: '6️⃣', zebra: '🦓',
  flag: '🚩', crab: '🦀', snail: '🐌', sled: '🛷', plane: '✈️', grapes: '🍇', swan: '🦢', skate: '⛸️', glove: '🧤', plant: '🪴', truck: '🚚', stamp: '📮', block: '🧱', lock: '🔒',
  ship: '🚢', chick: '🐤', cheese: '🧀', thumb: '👍', three: '3️⃣', whale: '🐋', brush: '🖌️', train: '🚆', rain: '🌧️', chain: '⛓️', coat: '🧥', skateboard: '🛹',
  turkey: '🦃', button: '🔘', kettle: '🫖', castle: '🏰', pumpkin: '🎃', popcorn: '🍿', puppet: '🧸', corn: '🌽', horn: '📯', fork: '🍴', shirt: '👕', girl: '👧', nurse: '🧑‍⚕️', shark: '🦈', farm: '🚜', purple: '🟣', park: '🏞️', storm: '⛈️', church: '⛪', peach: '🍑', teeth: '🦷',
  mug: '☕', hand: '✋', egg: '🥚', ant: '🐜', umbrella: '☂️', octopus: '🐙', elephant: '🐘', bell: '🔔', sock2: '🧦',
};

// ---------- Pre-K / K: listening games ----------
// Rhyme: [spoken word, rhyming picture, non-rhyming pictures]
export const RHYME = [
  ['cat', 'hat', ['sun', 'dog']], ['dog', 'log', ['cake', 'moon']], ['bee', 'tree', ['fox', 'car']], ['cake', 'snake', ['bus', 'fish']],
  ['king', 'ring', ['hen', 'boat']], ['moon', 'spoon', ['pig', 'cat']], ['bear', 'chair', ['sun', 'duck']], ['boat', 'goat', ['bed', 'king']],
  ['mouse', 'house', ['frog', 'cake']], ['car', 'star', ['pig', 'bus']], ['sock', 'clock', ['bee', 'hat']], ['nose', 'rose', ['bat', 'dog']],
  ['hen', 'ten', ['moon', 'fox']], ['fox', 'box', ['star', 'bee']], ['bug', 'mug', ['cake', 'moon']], ['bed', 'bread', ['king', 'sock']],
];
// First sound: [spoken word, picture that starts the same, other pictures, first letter]
export const FIRST = [
  ['ball', 'bear', ['sun', 'fish'], 'b'], ['moon', 'mouse', ['cat', 'tree'], 'm'], ['sun', 'sock', ['ball', 'dog'], 's'], ['fish', 'fox', ['moon', 'hat'], 'f'],
  ['dog', 'duck', ['sun', 'king'], 'd'], ['cat', 'car', ['moon', 'fish'], 'c'], ['tree', 'turtle', ['ball', 'nose'], 't'], ['pig', 'pen', ['sun', 'goat'], 'p'],
  ['hat', 'horse', ['moon', 'bus'], 'h'], ['nose', 'nut', ['cake', 'fish'], 'n'], ['rabbit', 'ring', ['dog', 'moon'], 'r'], ['goat', 'gift', ['sun', 'hat'], 'g'],
  ['lion', 'leaf', ['bus', 'cat'], 'l'], ['king', 'key', ['sun', 'bear'], 'k'], ['web', 'whale', ['fox', 'moon'], 'w'], ['zebra', 'zebra', ['hat', 'dog'], 'z'],
];
export const LETTERS = 'ABCDEFGHIJKLMNOPRSTUW'.split('');

// ---------- K / Grade 1: short vowels ----------
export const CVC = ['cat', 'hat', 'bat', 'map', 'van', 'pig', 'pin', 'fox', 'box', 'log', 'sun', 'bus', 'nut', 'bug', 'bed', 'hen', 'web', 'net', 'ten', 'dog'];
// ---------- Grade 1-2: blends and digraphs ----------
export const BLENDS = [['frog', 'fr'], ['flag', 'fl'], ['clock', 'cl'], ['crab', 'cr'], ['drum', 'dr'], ['star', 'st'], ['snail', 'sn'], ['sled', 'sl'], ['plane', 'pl'], ['tree', 'tr'], ['grapes', 'gr'], ['bread', 'br'], ['spoon', 'sp'], ['swan', 'sw'], ['skate', 'sk'], ['glove', 'gl'], ['plant', 'pl'], ['truck', 'tr']];
export const BLEND_SET = ['fr', 'fl', 'cl', 'cr', 'dr', 'st', 'sn', 'sl', 'pl', 'tr', 'gr', 'br', 'sp', 'sw', 'sk', 'gl'];
// [word, digraph, position]
export const DIGRAPHS = [['ship', 'sh', 0], ['sheep', 'sh', 0], ['shell', 'sh', 0], ['chick', 'ch', 0], ['chair', 'ch', 0], ['cheese', 'ch', 0], ['thumb', 'th', 0], ['three', 'th', 0], ['whale', 'wh', 0], ['wheat', 'wh', 0], ['duck', 'ck', 1], ['sock', 'ck', 1], ['fish', 'sh', 1], ['brush', 'sh', 1], ['peach', 'ch', 1], ['teeth', 'th', 1]];
// ---------- K end / Grade 1: magic e (short vs long) ----------
export const MAGIC_E = [['cap', 'cape'], ['tap', 'tape'], ['mad', 'made'], ['can', 'cane'], ['hat', 'hate'], ['kit', 'kite'], ['pin', 'pine'], ['bit', 'bite'], ['rid', 'ride'], ['dim', 'dime'], ['hop', 'hope'], ['not', 'note'], ['rob', 'robe'], ['cub', 'cube'], ['tub', 'tube'], ['cut', 'cute'], ['pet', 'Pete'], ['fin', 'fine']];
// ---------- Grade 2-3: r-controlled vowels ----------
// [word, pattern, clue]
export const RCTRL = [['star', 'ar', 'It twinkles in the night sky.'], ['car', 'ar', 'You ride in it on the road.'], ['farm', 'ar', 'A place with barns, fields, and animals.'], ['park', 'ar', 'A place with grass and trees to play.'], ['shark', 'ar', 'A big fish with sharp teeth.'], ['yard', 'ar', 'The grassy space around a house.'],
  ['horn', 'or', 'A shofar is one kind. You blow it.'], ['corn', 'or', 'Yellow kernels on a cob.'], ['fork', 'or', 'You eat with it.'], ['storm', 'or', 'Wind, rain, and thunder.'], ['north', 'or', 'The opposite of south.'], ['horse', 'or', 'An animal you can ride.'],
  ['bird', 'ir', 'It has feathers and can fly.'], ['girl', 'ir', 'A young woman.'], ['shirt', 'ir', 'You wear it on your top half.'], ['first', 'ir', 'Number one in line.'],
  ['turtle', 'ur', 'A slow animal with a shell.'], ['purple', 'ur', 'A color made from red and blue.'], ['nurse', 'ur', 'A person who cares for sick people.'], ['church', 'ur', 'A place where people worship God.'],
  ['her', 'er', 'A word for a girl or woman.'], ['fern', 'er', 'A leafy green plant.'], ['sister', 'er', 'A girl in your family.'], ['winter', 'er', 'The coldest season.']];
export const OA = [['boat', 'A small ship.'], ['coat', 'You wear it when it is cold.'], ['goat', 'A farm animal with horns.'], ['road', 'Cars drive on it.'], ['soap', 'You wash with it.'], ['toast', 'Warm, crunchy bread.'], ['float', 'To stay on top of the water.'], ['coach', 'A person who trains a team.']];

// ---------- Syllables by level (hyphens mark the parts) ----------
export const SYLL_L = {
  2: ['bath-tub', 'pop-corn', 'hill-top', 'back-pack', 'sand-box', 'cob-web', 'sun-set', 'kit-ten'],
  3: ['sun-set', 'bas-ket', 'pic-nic', 'kit-ten', 'rab-bit', 'nap-kin', 'cup-cake', 'rain-bow'],
  4: ['moun-tain', 'shep-herd', 'prom-ise', 'peace-ful', 'broth-er', 'for-give', 'a-fraid', 'tab-let'],
  5: ['won-der-ful', 'bi-cy-cle', 'ad-ven-ture', 'cel-e-brate', 'fan-tas-tic', 'dis-cov-er', 're-mem-ber', 'an-i-mal', 'to-geth-er', 'gen-er-ous'],
  6: ['tel-e-scope', 'in-for-ma-tion', 'dif-fer-ent', 'cat-er-pil-lar', 'im-pos-si-ble', 're-spon-si-ble', 'cov-e-nant', 'com-mand-ment'],
  7: ['per-se-ver-ance', 'op-por-tu-ni-ty', 'mag-nif-i-cent', 'pho-to-syn-the-sis', 'in-de-pen-dent', 'Sa-mar-i-tan'],
  8: ['ex-tra-or-di-nar-y', 'ac-com-plish-ment', 'com-mu-ni-ca-tion', 'in-ev-i-ta-ble', 'con-sid-er-a-tion', 're-spon-si-bil-i-ty'],
  9: ['cir-cum-stan-tial', 'in-ter-na-tion-al', 'mis-cel-la-ne-ous', 'en-thu-si-as-tic', 'char-ac-ter-is-tic', 'ex-ag-ger-a-tion'],
};
// ---------- Spelling: [word, level, clue, three misspellings] ----------
export const SPELL = [
  ['frog', 2, 'A green animal that hops.', ['frogg', 'forg', 'frug']], ['ship', 2, 'A big boat.', ['shipp', 'chip', 'sihp']], ['black', 2, 'The darkest color.', ['blak', 'blakc', 'bleck']], ['lunch', 2, 'A meal in the middle of the day.', ['lunsh', 'lonch', 'lunc']], ['think', 2, 'To use your mind.', ['thinc', 'thenk', 'fink']], ['jump', 2, 'To push off the ground with your feet.', ['jumb', 'jupm', 'gump']],
  ['rain', 3, 'Water that falls from clouds.', ['rane', 'rayn', 'rian']], ['boat', 3, 'It floats on water.', ['bote', 'boet', 'bowt']], ['cake', 3, 'A sweet treat for a birthday.', ['caik', 'kake', 'cak']], ['night', 3, 'The dark time after the sun sets.', ['nite', 'nigt', 'niht']], ['green', 3, 'The color of grass.', ['grean', 'gren', 'grene']], ['star', 3, 'It shines in the night sky.', ['stor', 'starr', 'sdar']],
  ['careful', 4, 'Paying close attention so nothing goes wrong.', ['carefull', 'carful', 'kareful']], ['friend', 4, 'Someone you like and trust.', ['freind', 'frend', 'friand']], ['because', 4, 'A word that gives a reason.', ['becuase', 'becauze', 'becuz']], ['cloud', 4, 'White and fluffy in the sky.', ['clowd', 'claud', 'cloude']], ['coin', 4, 'Round metal money.', ['coyn', 'coine', 'cion']], ['happy', 4, 'Feeling glad.', ['happi', 'hapy', 'happey']],
  ['beautiful', 5, 'Very lovely to see or hear.', ['beautifull', 'beutiful', 'butiful']], ['different', 5, 'Not the same.', ['diffrent', 'diferent', 'differant']], ['believe', 5, 'To think something is true.', ['beleive', 'belive', 'beleave']], ['through', 5, 'In one side and out the other.', ['thru', 'throgh', 'threw']], ['enough', 5, 'As much as you need.', ['enuff', 'enogh', 'enouf']], ['favorite', 5, 'The one you like best.', ['favrite', 'faverite', 'favorit']],
  ['necessary', 6, 'Needed; must be done.', ['neccessary', 'necesary', 'nessesary']], ['separate', 6, 'To pull apart, or kept apart.', ['seperate', 'separat', 'seprate']], ['business', 6, 'A company, or work that someone does.', ['buisness', 'busness', 'bizness']], ['definitely', 6, 'Without any doubt.', ['definately', 'definitly', 'defanitely']], ['calendar', 6, 'A chart of days, weeks, and months.', ['calender', 'calandar', 'callendar']], ['disciple', 6, 'A follower who learns from a teacher.', ['diciple', 'disiple', 'dissiple']],
  ['environment', 7, 'The natural world around us.', ['enviroment', 'environmant', 'envirnment']], ['rhythm', 7, 'A steady beat in music.', ['rythm', 'rhythem', 'rhytm']], ['government', 7, 'The group that leads a country.', ['goverment', 'govenment', 'governmant']], ['occasion', 7, 'A special event or time.', ['ocasion', 'occassion', 'occation']], ['conscience', 7, 'The inner sense of right and wrong.', ['concience', 'consience', 'conscence']], ['Pharaoh', 7, 'The title of the king of ancient Egypt.', ['Pharoah', 'Farao', 'Pharao']],
  ['accommodate', 8, 'To make room for or provide for.', ['accomodate', 'acommodate', 'accomadate']], ['embarrass', 8, 'To make someone feel awkward or ashamed.', ['embarass', 'embarras', 'imbarrass']], ['privilege', 8, 'A special right or advantage.', ['privelege', 'priviledge', 'privilage']], ['recommend', 8, 'To suggest as good or worthwhile.', ['reccomend', 'recomend', 'reccommend']], ['guarantee', 8, 'A firm promise.', ['garantee', 'guarentee', 'guarante']], ['perseverance', 8, 'Continuing to try even when it is hard.', ['perseverence', 'perserverance', 'persevarance']],
  ['conscientious', 9, 'Careful and eager to do what is right.', ['consciencious', 'conscientous', 'consientious']], ['bureaucracy', 9, 'A system of officials and many rules.', ['beaurocracy', 'bureacracy', 'burocracy']], ['silhouette', 9, 'A dark outline against a light background.', ['silouette', 'silhouete', 'sillhouette']], ['questionnaire', 9, 'A written set of questions.', ['questionaire', 'questionnare', 'questionnaier']], ['entrepreneur', 9, 'A person who starts a business.', ['entrepeneur', 'entreprenuer', 'enterpreneur']], ['Deuteronomy', 9, 'The fifth book of the Bible.', ['Deutoronomy', 'Deuteronemy', 'Duteronomy']],
];

// ---------- Sight words (Dolch pre-primer to 3rd grade; Fry for grade 4) ----------
// [sentence with ___, answer, distractors, level]
export const SIGHT = [
  ['I can ___ the dog.', 'see', ['sea', 'she'], 1], ['The cat is ___.', 'big', ['bag', 'dig'], 1], ['We like to ___.', 'play', ['pay', 'plan'], 1], ['Look at ___ hat.', 'my', ['me', 'may'], 1], ['The ball is ___.', 'red', ['read', 'rod'], 1], ['I can ___ fast.', 'run', ['ran', 'rub'], 1], ['___ is my mom.', 'She', ['He', 'See'], 1], ['I ___ a book.', 'have', ['hive', 'gave'], 1],
  ['Please ___ me the cup.', 'give', ['gave', 'live'], 2], ['I ___ how to swim.', 'know', ['now', 'knot'], 2], ['The bird can ___.', 'fly', ['fry', 'flip'], 2], ['Can you ___ the door?', 'open', ['over', 'oven'], 2], ['We ___ to the park.', 'walk', ['talk', 'wake'], 2], ['___ upon a time, there was a king.', 'Once', ['One', 'Open'], 2], ['Thank you ___ the gift.', 'for', ['from', 'fur'], 2], ['I ___ it is time to go.', 'think', ['thank', 'thing'], 2],
  ['I ___ say my prayers.', 'always', ['away', 'also'], 3], ['I stayed in ___ it was raining.', 'because', ['before', 'became'], 3], ['___ is the sky blue?', 'Why', ['Who', 'Way'], 3], ['I ___ my hands before I eat.', 'wash', ['wish', 'was'], 3], ['Please ___ your name here.', 'write', ['white', 'wrote'], 3], ['___ shoes are by the door.', 'Your', ['You', 'Our'], 3], ['He ___ his lunch with me.', 'shared', ['shaded', 'showed'], 3], ['This is the ___ day ever!', 'best', ['bust', 'beast'], 3],
  ['Please ___ your Bible to church.', 'bring', ['being', 'brown'], 4], ['Can you ___ the water jar?', 'carry', ['cry', 'cart'], 4], ['God is ___ to us.', 'kind', ['find', 'king'], 4], ['The lamp gives ___.', 'light', ['like', 'night'], 4], ['We work ___ as a team.', 'together', ['tomorrow', 'toward'], 4], ['God will ___ leave you.', 'never', ['even', 'over'], 4], ['Seeds ___ into plants.', 'grow', ['grew', 'glow'], 4], ['My basket is ___ of bread.', 'full', ['fall', 'fill'], 4],
  ['We walked ___ the forest to the river.', 'through', ['though', 'thorough'], 5], ['There was ___ food for everyone.', 'enough', ['enjoy', 'even'], 5], ['The trip took ___ days.', 'several', ['severe', 'seven'], 5], ['He sat ___ his friends.', 'among', ['along', 'amount'], 5], ['It rained ___ the night.', 'during', ['daring', 'doing'], 5], ['She ate the ___ sandwich.', 'whole', ['hole', 'while'], 5], ['I am ___ that God loves me.', 'certain', ['curtain', 'captain'], 5], ['___ it was cold, we went outside.', 'Although', ['Already', 'Always'], 5],
];

// ---------- Vocabulary by level: child-friendly meaning + example ----------
// pic: emoji for picture levels (0-3). Meanings are short so they work as quiz choices.
const V = (w, lv, def, ex, pic) => ({ w, lv, def, ex, pic: pic || null });
export const VOCAB = [
  V('dog', 0, 'A pet that barks and wags its tail.', 'The dog wagged its tail.', '🐶'), V('apple', 0, 'A round red or green fruit.', 'I ate a crunchy apple.', '🍎'), V('ball', 0, 'A round toy you can throw or kick.', 'Kick the ball to me.', '⚽'), V('shoe', 0, 'You wear it on your foot.', 'Put on your shoe.', '👟'), V('bird', 0, 'An animal with feathers and wings.', 'A bird sang in the tree.', '🐦'), V('banana', 0, 'A long yellow fruit.', 'I peeled a banana.', '🍌'), V('car', 0, 'You ride in it on the road.', 'We drove in the car.', '🚗'), V('fish', 0, 'An animal that swims in water.', 'The fish swam in the sea.', '🐟'), V('moon', 0, 'It shines in the sky at night.', 'God made the moon to light the night.', '🌙'), V('house', 0, 'A building where people live.', 'Our house has a red door.', '🏠'),
  V('carrot', 1, 'A long orange vegetable.', 'The rabbit ate a carrot.', '🥕'), V('drum', 1, 'You tap it to make music.', 'He played the drum.', '🥁'), V('ladder', 1, 'You climb it to reach high places.', 'Dad climbed the ladder.', '🪜'), V('turtle', 1, 'A slow animal with a hard shell.', 'The turtle hid in its shell.', '🐢'), V('rabbit', 1, 'A small animal with long ears that hops.', 'The rabbit hopped away.', '🐰'), V('camel', 1, 'A desert animal with a hump.', 'The camel walked across the sand.', '🐫'), V('bread', 1, 'Food baked from flour.', 'A boy shared his bread.', '🍞'), V('rainbow', 1, 'Colors in the sky after rain.', 'God put a rainbow in the sky.', '🌈'), V('basket', 1, 'A woven container for carrying things.', 'Twelve baskets were full of food.', '🧺'), V('candle', 1, 'Wax with a wick that you light.', 'The candle glowed softly.', '🕯️'),
  V('penguin', 2, 'A black and white bird that swims but cannot fly.', 'The penguin slid on the ice.', '🐧'), V('bridge', 2, 'Something built to cross over water or a road.', 'We walked across the bridge.', '🌉'), V('anchor', 2, 'A heavy hook that holds a ship in place.', 'The sailors dropped the anchor.', '⚓'), V('feather', 2, 'A light, soft part of a bird’s covering.', 'A white feather floated down.', '🪶'), V('shell', 2, 'The hard outside covering of some sea animals.', 'I found a shell on the beach.', '🐚'), V('crown', 2, 'A ring of gold a king or queen wears.', 'The king wore a golden crown.', '👑'), V('lamp', 2, 'Something that gives light.', 'God’s Word is a lamp to my feet.', '🪔'), V('owl', 2, 'A bird with big eyes that is awake at night.', 'The owl hooted in the dark.', '🦉'), V('tent', 2, 'A cloth shelter held up with poles.', 'Abraham lived in a tent.', '⛺'), V('key', 2, 'A small metal tool that opens a lock.', 'She turned the key in the door.', '🔑'),
  V('volcano', 3, 'A mountain that can erupt with hot melted rock.', 'Smoke rose from the volcano.', '🌋'), V('cactus', 3, 'A spiky desert plant that stores water.', 'A cactus can live without much rain.', '🌵'), V('compass', 3, 'A tool that shows which way is north.', 'The hiker checked her compass.', '🧭'), V('microscope', 3, 'A tool that makes tiny things look bigger.', 'We saw cells with a microscope.', '🔬'), V('telescope', 3, 'A tool for seeing things far away.', 'She looked at the stars through a telescope.', '🔭'), V('scroll', 3, 'A long roll of paper or leather with writing.', 'Jesus read from a scroll.', '📜'), V('trumpet', 3, 'A brass instrument you blow into.', 'The trumpet played a loud note.', '🎺'), V('wheat', 3, 'A grain used to make flour and bread.', 'The farmer cut the wheat.', '🌾'), V('dove', 3, 'A gentle bird often used as a sign of peace.', 'The dove brought Noah an olive leaf.', '🕊️'), V('globe', 3, 'A round model of the earth.', 'Find the ocean on the globe.', '🌍'),
  V('enormous', 4, 'Very, very big.', 'Noah built an enormous ark.'), V('fragile', 4, 'Easy to break.', 'Carry the fragile jar carefully.'), V('protect', 4, 'To keep safe from harm.', 'A shepherd protects his sheep.'), V('gather', 4, 'To bring together into one place.', 'The disciples gathered the leftover bread.'), V('journey', 4, 'A long trip.', 'The journey to Egypt took many days.'), V('ancient', 4, 'Very, very old.', 'We saw an ancient scroll.'), V('whisper', 4, 'To speak very softly.', 'She whispered a secret.'), V('shelter', 4, 'A place that keeps you safe from weather.', 'The tent gave us shelter from the rain.'), V('curious', 4, 'Wanting to know or learn more.', 'The curious boy asked many questions.'), V('village', 4, 'A small town.', 'The village had one well.'),
  V('reluctant', 5, 'Not wanting to do something.', 'Moses was reluctant to speak at first.'), V('observe', 5, 'To watch carefully.', 'We observed the birds building a nest.'), V('patient', 5, 'Able to wait calmly.', 'Be patient while the bread bakes.'), V('cautious', 5, 'Careful to avoid danger.', 'Be cautious near the edge of the cliff.'), V('abundant', 5, 'More than enough.', 'The harvest was abundant.'), V('humble', 5, 'Not proud or boastful.', 'A humble person does not brag.'), V('exhausted', 5, 'Very, very tired.', 'After the long climb, we were exhausted.'), V('scarce', 5, 'Hard to find; not enough.', 'Food was scarce during the famine.'), V('predict', 5, 'To say what will happen before it happens.', 'Can you predict the ending of the story?'), V('generous', 5, 'Happy to share with others.', 'The boy was generous with his lunch.'),
  V('evidence', 6, 'Facts that show something is true.', 'The muddy boots were evidence that he went outside.'), V('conclude', 6, 'To decide after thinking about the facts.', 'We concluded that the plant needed more sun.'), V('habitat', 6, 'The natural home of a plant or animal.', 'The desert is a camel’s habitat.'), V('persuade', 6, 'To get someone to agree by giving reasons.', 'She persuaded her brother to share.'), V('temporary', 6, 'Lasting only a short time.', 'The tent was a temporary home.'), V('essential', 6, 'Very important; needed.', 'Water is essential for life.'), V('consequence', 6, 'Something that happens because of an action.', 'A consequence of lying is losing trust.'), V('compassion', 6, 'Caring about someone’s trouble and wanting to help.', 'The Samaritan showed compassion.'), V('frequent', 6, 'Happening often.', 'We take frequent breaks on long walks.'), V('restore', 6, 'To bring back to how it was.', 'They worked to restore the old fence.'),
  V('analyze', 7, 'To study the parts of something closely.', 'Scientists analyze data to find patterns.'), V('significant', 7, 'Important; worth noticing.', 'The rainbow was a significant sign.'), V('perspective', 7, 'A way of seeing things; a point of view.', 'Try to see it from your friend’s perspective.'), V('contrast', 7, 'To show how things are different.', 'Contrast the priest with the Samaritan.'), V('adapt', 7, 'To change to fit a new situation.', 'Joseph adapted to life in Egypt.'), V('diligent', 7, 'Working hard and carefully.', 'Noah was diligent in building the ark.'), V('integrity', 7, 'Being honest and doing right even when no one is watching.', 'Integrity means telling the truth when it is hard.'), V('resilient', 7, 'Able to recover after something hard.', 'Joseph stayed resilient through hard years.'), V('infer', 7, 'To figure something out from clues.', 'From the wet ground, we can infer that it rained.'), V('prosper', 7, 'To do well; to succeed.', 'Egypt prospered under Joseph’s planning.'),
  V('inevitable', 8, 'Sure to happen; cannot be avoided.', 'Mistakes are inevitable when you learn something new.'), V('ambiguous', 8, 'Having more than one possible meaning; unclear.', 'The message was ambiguous, so we asked what it meant.'), V('advocate', 8, 'To speak up in support of someone or something.', 'She advocated for kids who needed help.'), V('implicit', 8, 'Suggested but not said directly.', 'There was an implicit promise in his smile.'), V('meager', 8, 'Very small in amount; barely enough.', 'The boy’s meager lunch fed thousands.'), V('candid', 8, 'Honest and direct.', 'Thank you for your candid answer.'), V('reconcile', 8, 'To become friendly again after a disagreement.', 'Joseph reconciled with his brothers.'), V('tedious', 8, 'Long, slow, and boring.', 'Sorting the grain was tedious work.'), V('verify', 8, 'To check that something is true.', 'Verify the facts before you share them.'), V('deteriorate', 8, 'To get worse over time.', 'The old fence began to deteriorate.'),
  V('meticulous', 9, 'Extremely careful about details.', 'Noah followed God’s plan with meticulous care.'), V('pragmatic', 9, 'Dealing with things in a practical way.', 'Joseph’s plan to store grain was pragmatic.'), V('benevolent', 9, 'Kind and wanting to do good.', 'The benevolent king fed the hungry.'), V('ubiquitous', 9, 'Found everywhere.', 'Phones are ubiquitous today.'), V('ephemeral', 9, 'Lasting a very short time.', 'A rainbow is beautiful but ephemeral.'), V('eloquent', 9, 'Speaking clearly and powerfully.', 'Moses felt he was not eloquent.'), V('magnanimous', 9, 'Generous and forgiving, especially toward a rival.', 'Joseph was magnanimous toward his brothers.'), V('superfluous', 9, 'More than is needed; extra.', 'Cut the superfluous words from your essay.'), V('tenacious', 9, 'Holding on; not giving up.', 'The tenacious climber reached the summit.'), V('scrutinize', 9, 'To examine very closely.', 'The editor scrutinized every sentence.'),
];
export const vocabAt = lv => VOCAB.filter(v => v.lv === lv);
// Synonyms (grades 6-8): [level, word, synonym, distractors]
export const SYN = [
  [7, 'rapid', 'fast', ['quiet', 'heavy', 'early']], [7, 'conceal', 'hide', ['build', 'repair', 'borrow']], [7, 'fatigue', 'tiredness', ['anger', 'courage', 'surprise']], [7, 'ample', 'plenty', ['narrow', 'silent', 'sudden']],
  [8, 'obstinate', 'stubborn', ['cheerful', 'clumsy', 'generous']], [8, 'diminish', 'shrink', ['repeat', 'gather', 'decorate']], [8, 'lethargic', 'sluggish', ['grateful', 'nervous', 'curious']], [8, 'prudent', 'wise', ['noisy', 'careless', 'ancient']],
  [9, 'benevolent', 'kind', ['greedy', 'timid', 'clever']], [9, 'ephemeral', 'short-lived', ['ancient', 'costly', 'enormous']], [9, 'tenacious', 'persistent', ['careless', 'graceful', 'fearful']], [9, 'laconic', 'brief', ['loud', 'colorful', 'sudden']],
];
// Prefixes, suffixes, Greek and Latin roots: [level, question, answer, distractors]
export const AFFIX = [
  [3, 'Which word means “to lock again”?', 'relock', ['locked', 'locker', 'locking']], [3, 'Which word means “the opposite of lock”?', 'unlock', ['locked', 'locker', 'relock']], [3, 'Which word means “full of help”?', 'helpful', ['helper', 'helped', 'helping']], [3, 'Which word means “without use”?', 'useless', ['useful', 'used', 'user']], [3, 'Which word means “to fill again”?', 'refill', ['filled', 'filling', 'unfilled']], [3, 'Which word means “not kind”?', 'unkind', ['kindly', 'kinder', 'kindest']],
  [4, 'Which word means “not happy”?', 'unhappy', ['happily', 'happier', 'happiness']], [4, 'Which word means “to play again”?', 'replay', ['player', 'playful', 'display']], [4, 'Which word means “full of hope”?', 'hopeful', ['hopeless', 'hoping', 'hoped']], [4, 'Which word means “without fear”?', 'fearless', ['fearful', 'feared', 'fearing']], [4, 'Which word means “a person who teaches”?', 'teacher', ['teaching', 'taught', 'teaches']],
  [5, 'Which word means “not possible”?', 'impossible', ['possibly', 'possibility', 'possibilities']], [5, 'Which word means “understood wrongly”?', 'misunderstood', ['understood', 'understanding', 'understandable']], [5, 'What does the prefix dis- mean in disagree?', 'not, or the opposite of', ['again', 'before', 'full of']], [5, 'What does the suffix -ful mean in careful?', 'full of', ['without', 'again', 'not']], [5, 'Which word means “able to be washed”?', 'washable', ['washer', 'washing', 'unwashed']],
  [6, 'Tele means far. Which word names a tool for seeing far away?', 'telescope', ['microscope', 'stethoscope', 'horoscope']], [6, 'Graph means write. Which word means a person’s own signed name?', 'autograph', ['photograph', 'paragraph', 'biography']], [6, 'Bio means life. Biology is the study of…', 'living things', ['rocks and soil', 'stars and planets', 'numbers']], [6, 'Re- means again. What does reconstruct mean?', 'build again', ['take apart', 'build first', 'build badly']], [6, 'Pre- means before. A preview is…', 'a look ahead of time', ['a look afterward', 'a very long look', 'a look from far away']],
  [7, 'Port means carry. Which word means to carry goods out of a country?', 'export', ['import', 'report', 'support']], [7, 'Spect means look. A spectator is someone who…', 'watches an event', ['coaches the team', 'sells the tickets', 'builds the stadium']], [7, 'Dict means say. To predict is to…', 'say what will happen before it happens', ['say something again', 'speak very loudly', 'disagree with someone']], [7, 'Chron means time. Chronological order is…', 'time order', ['size order', 'color order', 'alphabetical order']], [7, 'Aqua means water. An aquarium holds…', 'water animals and plants', ['desert animals', 'old books', 'sand and rocks']],
  [8, 'Bene means good. A benefit is…', 'something good you receive', ['a kind of bench', 'a harmful mistake', 'a long delay']], [8, 'Mal means bad. A malfunction is…', 'a failure to work properly', ['a new invention', 'a big party', 'a quick repair']], [8, 'Contra means against. To contradict is to…', 'say the opposite', ['agree completely', 'repeat word for word', 'speak quietly']], [8, 'Omni means all. An omnivore eats…', 'both plants and animals', ['only plants', 'only meat', 'only fish']], [8, 'Ject means throw. To reject is to…', 'refuse or turn away', ['accept gladly', 'build again', 'look closely']],
  [9, 'Meter means measure. A chronometer measures…', 'time', ['distance', 'heat', 'weight']], [9, 'Anthrop means human. Anthropology studies…', 'human societies and cultures', ['ancient plants', 'ocean currents', 'distant planets']], [9, 'Philo means love and soph means wisdom. Philosophy literally means…', 'love of wisdom', ['fear of books', 'study of stars', 'rule by many']], [9, 'Bene means good and dict means say. A benediction is…', 'a spoken blessing', ['a harsh rule', 'a list of complaints', 'a kind of dictionary']], [9, 'Circum means around. To circumnavigate is to…', 'sail all the way around', ['sail straight across', 'sink under the water', 'stay in the harbor']],
];
// Context clues: [level, sentence, word, meaning, distractors]
export const CONTEXT = [
  [5, 'The desert was so arid that no plants could grow.', 'arid', 'very dry', ['very cold', 'very crowded', 'very noisy']], [5, 'Noah was weary after a long day of building, so he sat down to rest.', 'weary', 'tired', ['excited', 'hungry', 'angry']], [5, 'The lamb was docile and let the children pet it gently.', 'docile', 'calm and gentle', ['wild and fast', 'sick and weak', 'tiny and quiet']], [5, 'Andrew was astonished when the small lunch fed the whole crowd.', 'astonished', 'very surprised', ['bored', 'upset', 'sleepy']],
  [6, 'The field was barren; not a single plant or flower grew there.', 'barren', 'having no plants', ['full of flowers', 'freshly painted', 'very small']], [6, 'Joseph was prudent; he stored grain in good years to prepare for hard ones.', 'prudent', 'wise and careful about the future', ['lazy and forgetful', 'rich and proud', 'quick and noisy']], [6, 'The brook was so transparent that David could see the stones at the bottom.', 'transparent', 'clear enough to see through', ['muddy and dark', 'fast and loud', 'very deep']], [6, 'The speaker was concise, explaining the plan in two short sentences.', 'concise', 'brief and clear', ['long and confusing', 'loud and angry', 'shy and quiet']],
  [7, 'The inn was dilapidated, with a sagging roof and broken windows.', 'dilapidated', 'falling apart', ['brand new', 'very crowded', 'brightly painted']], [7, 'Although Moses felt apprehensive about speaking, he trusted God and went anyway.', 'apprehensive', 'worried or nervous', ['proud and excited', 'bored', 'angry']], [7, 'The crowd grew boisterous, cheering and shouting as the band marched by.', 'boisterous', 'loud and full of energy', ['silent and still', 'sad and tearful', 'tired and sleepy']], [7, 'Her explanation was so lucid that everyone understood the problem at once.', 'lucid', 'clear and easy to understand', ['long and dull', 'strange and scary', 'quick and careless']],
  [8, 'Unlike his gregarious sister, who loved parties, Eli preferred quiet evenings alone.', 'gregarious', 'enjoying being with other people', ['afraid of the dark', 'good at math', 'often sleepy']], [8, 'The evidence was irrefutable; no one could argue that it was wrong.', 'irrefutable', 'impossible to prove wrong', ['easy to lose', 'hard to find', 'probably false']], [8, 'The coach’s praise was sparing; she rarely handed out compliments.', 'sparing', 'given in small amounts', ['given very often', 'loud and silly', 'written down']], [8, 'The old map was so obscure that even the experts could not read it.', 'obscure', 'hard to see or understand', ['bright and colorful', 'brand new', 'very large']],
  [9, 'The treaty was ratified after every nation voted to approve it.', 'ratified', 'officially approved', ['torn up', 'kept secret', 'written in pencil']], [9, 'His apology seemed perfunctory, mumbled quickly without any real feeling.', 'perfunctory', 'done quickly with little care', ['deeply sincere', 'very long', 'sung aloud']], [9, 'Joseph showed clemency toward his brothers, forgiving them instead of punishing them.', 'clemency', 'mercy', ['anger', 'wealth', 'confusion']], [9, 'The decision was unanimous; every member of the committee voted yes.', 'unanimous', 'agreed on by everyone', ['decided by one person', 'still undecided', 'mostly rejected']],
];

// ---------- Game catalogue ----------
// lv: [min, max] reading level (vocab games use the vocabulary level). pre = shown to pre-readers.
export const GAMES = [
  { id: 'rhyme', title: 'Rhyme Time', skill: 'rhyme', lv: [0, 1], pre: true, dir: 'Listen to the word. Tap the picture that rhymes with it.', tip: 'Rhyming words sound the same at the end, like cat and hat.' },
  { id: 'first', title: 'First Sounds', skill: 'first', lv: [0, 2], pre: true, dir: 'Listen to the word. Find the one that starts with the same sound.', tip: 'Say the word slowly. Listen to the very first sound.' },
  { id: 'letters', title: 'Letter Hunt', skill: 'letters', lv: [0, 1], pre: true, dir: 'Listen. Tap the letter you hear.', tip: 'Look at the shape of each letter.' },
  { id: 'cvc', title: 'Missing Vowel', skill: 'cvc', lv: [1, 2], dir: 'Look at the picture. Pick the vowel that finishes the word.', tip: 'Say the word slowly: c - a - t.' },
  { id: 'bd', title: 'b or d?', skill: 'bd', lv: [1, 3], dir: 'Look at the picture. Pick the first letter: b or d.', tip: 'Make a “bed” with your fists: b is on the left, d is on the right.' },
  { id: 'blend', title: 'Blend Builder', skill: 'blend', lv: [2, 3], dir: 'Look at the picture. Pick the blend that starts the word.', tip: 'Say the blend slowly: f-r, fr.' },
  { id: 'digraph', title: 'Digraph Detective', skill: 'digraph', lv: [2, 3], dir: 'Look at the picture. Pick the two letters that make the missing sound.', tip: 'sh, ch, th, wh, and ck are two letters that make one sound.' },
  { id: 'sort_ai', title: 'Sort It: ai or ay', skill: 'vowel', lv: [3, 4], dir: 'Read the word. Drag it, or tap a box, to put it where it belongs.', tip: 'ai is usually at the start or middle of a word. ay is usually at the end.' },
  { id: 'sort_ee', title: 'Sort It: ee or ea', skill: 'vowel', lv: [3, 4], dir: 'Read the word. Drag it, or tap a box, to put it where it belongs.', tip: 'ee and ea can make the same sound. Look closely at each word.' },
  { id: 'fill_vt', title: 'Missing Vowel Team', skill: 'vowel', lv: [3, 4], dir: 'A vowel team is missing. Pick the letters that finish the word.', tip: 'Read the clue for help.' },
  { id: 'rctrl', title: 'Bossy R', skill: 'rctrl', lv: [3, 4], dir: 'The r changes the vowel sound. Pick the letters that finish the word.', tip: 'ar as in car, or as in fork, ir as in bird, ur as in turtle, er as in her.' },
  { id: 'diph', title: 'Diphthong Detective', skill: 'diph', lv: [4, 5], dir: 'Pick the letters that finish the word: oi, oy, ou, or ow.', tip: 'oi and ou are often in the middle. oy and ow are often at the end.' },
  { id: 'magic_e', title: 'Magic e', skill: 'magic', lv: [2, 3], dir: 'Read the word. Does it have a short vowel, or a long vowel made by magic e? Put it in the right box.', tip: 'cap has a short a. Add an e and it says cape, with a long a.' },
  { id: 'syll', title: 'Syllable Builder', skill: 'syll', lv: [3, 9], dir: 'Tap the word parts in order to build the word.', tip: 'Clap the parts: rain - bow.' },
  { id: 'sight', title: 'Sight Word Sentences', skill: 'sight', lv: [1, 5], dir: 'Read the sentence. Pick the word that fits in the blank.', tip: 'Read the whole sentence with your word in it.' },
  { id: 'spell', title: 'Pick the Right Spelling', skill: 'spell', lv: [2, 9], dir: 'Read the clue. Pick the word that is spelled correctly.', tip: 'Look at every letter.' },
  { id: 'affix', title: 'Word Parts', skill: 'affix', lv: [4, 9], dir: 'Use prefixes, suffixes, and roots to pick the best answer.', tip: 'Break the word into parts. What does each part mean?' },
  { id: 'context', title: 'Context Clues', skill: 'context', lv: [5, 9], dir: 'Read the sentence. Use the other words as clues to find what the bold word means.', tip: 'Look for words nearby that explain, contrast, or give an example.' },
  { id: 'vocab', title: 'Word Meanings', skill: 'vocab', lv: [0, 9], vocab: true, pre: true, dir: 'Listen to the word. Tap the picture or meaning that matches.', tip: 'Tap a speaker to hear any answer.' },
];
export const SKILL_NAMES = {
  rhyme: 'Rhyming', first: 'First Sounds', letters: 'Letter Names', cvc: 'Short Vowels (CVC)', bd: 'Letters b and d', blend: 'Consonant Blends', digraph: 'Digraphs (sh, ch, th)',
  vowel: 'Vowel Teams', rctrl: 'R-Controlled Vowels', magic: 'Magic e (Long Vowels)', diph: 'Diphthongs (oi, oy, ou, ow)', syll: 'Syllables', sight: 'Sight Words', spell: 'Spelling Patterns', affix: 'Prefixes, Suffixes, Roots', context: 'Context Clues', vocab: 'Vocabulary',
  elements: 'Story Elements', main: 'Main Idea', wh: 'Wh- Questions', retell: 'Retell / Sequencing', infer: 'Inference',
};
export const PHONICS_SKILLS = ['rhyme', 'first', 'letters', 'cvc', 'bd', 'blend', 'digraph', 'magic', 'vowel', 'rctrl', 'diph', 'syll', 'spell', 'affix', 'context'];
export const COMP_SKILLS = ['elements', 'main', 'wh', 'infer', 'retell'];
export const gamesFor = (readLv, vocabLv, school) => school ? schoolGames(GAMES, readLv).filter(g => readLv === 0 ? g.pre : true) : GAMES.filter(g => g.id !== 'magic_e' || (readLv >= 2 && readLv <= 3)).filter(g => readLv === 0 ? g.pre : (g.vocab ? true : readLv >= g.lv[0] && readLv <= g.lv[1]));
const COUNT = lv => lv <= 1 ? 6 : lv <= 3 ? 8 : 10;
const nCh = lv => lv <= 0 ? 2 : lv <= 2 ? 3 : 4;
const picOpt = w => ({ v: w, pic: PIC[w] || '❓', label: w });

// Build a list of items for a game. Item kinds: picchoice, letter, picfill, fill, sort, spell, sight, syll, mcq, bd
export function buildGame(id, readLv, vocabLv, school) {
  const g = GAMES.find(x => x.id === id); const lv = g.vocab ? vocabLv : readLv; const n = COUNT(lv); const items = [];
  const nc = nCh(lv);
  if (id === 'rhyme') for (const [w, r, others] of pickN(RHYME, n)) { const ch = shuffle([picOpt(r), ...others.slice(0, Math.max(1, nc - 1)).map(picOpt)]); items.push({ skill: 'rhyme', kind: 'picchoice', prompt: `Which one rhymes with ${w}?`, target: w, targetPic: PIC[w], choices: ch, answer: r, say: `${w}, ${r}` }); }
  else if (id === 'first') {
    for (const [w, same, others, letter] of pickN(FIRST.filter(f => f[0] !== f[1]), n)) {
      if (lv === 0) { const ch = shuffle([picOpt(same), ...others.map(picOpt)].slice(0, 3)); items.push({ skill: 'first', kind: 'picchoice', prompt: `Which one starts like ${w}?`, target: w, targetPic: PIC[w], choices: ch, answer: same, say: `${w}, ${same}` }); }
      else { const pool = shuffle('bcdfghklmnprstw'.split('').filter(x => x !== letter)).slice(0, nc - 1); items.push({ skill: 'first', kind: 'picfill', pic: PIC[w], prompt: `What sound does ${w} start with?`, word: '_' + w.slice(1), answer: letter, choices: shuffle([letter, ...pool]), say: w }); }
    }
  }
  else if (id === 'letters') for (const L of pickN(LETTERS, n)) { const lower = lv >= 1 && Math.random() < 0.5; const others = shuffle(LETTERS.filter(x => x !== L)).slice(0, lv === 0 ? 2 : 3); const f = x => lower ? x.toLowerCase() : x; items.push({ skill: 'letters', kind: 'letter', prompt: `Find the letter ${L}.`, answer: f(L), choices: shuffle([L, ...others]).map(f), say: `Find the letter ${L}.` }); }
  else if (id === 'cvc') for (const w of pickN(CVC, n)) { const v = w[1]; const others = shuffle('aeiou'.split('').filter(x => x !== v)).slice(0, lv <= 1 ? 1 : 2); items.push({ skill: 'cvc', kind: 'picfill', pic: PIC[w], word: w[0] + '_' + w[2], answer: v, choices: shuffle([v, ...others]), say: w }); }
  else if (id === 'bd') { const BD = [['dog', 'dog'], ['bed', 'bed'], ['bug', 'bug'], ['duck', 'duck'], ['book', 'book'], ['drum', 'drum'], ['bird', 'bird'], ['bread', 'bread'], ['bat', 'bat'], ['dove', 'dove']];
    for (const [w] of pickN(BD, lv <= 1 ? 6 : 8)) items.push({ skill: 'bd', kind: 'picfill', pic: PIC[w] || ({ book: '📖', bird: '🐦', dove: '🕊️' })[w], word: '_' + w.slice(1), answer: w[0], choices: ['b', 'd'], say: w, tip: 'Tip: make a “bed” with your fists. b is on the left, d is on the right.' }); }
  else if (id === 'blend') for (const [w, b] of pickN(BLENDS, n)) { const others = shuffle(BLEND_SET.filter(x => x !== b && x[0] !== b[0])).slice(0, nc - 1); items.push({ skill: 'blend', kind: 'picfill', pic: PIC[w], word: '__' + w.slice(2), answer: b, choices: shuffle([b, ...others]), say: w }); }
  else if (id === 'digraph') for (const [w, d, pos] of pickN(DIGRAPHS, n)) { const set = pos ? ['sh', 'ch', 'th', 'ck'] : ['sh', 'ch', 'th', 'wh']; const others = shuffle(set.filter(x => x !== d)).slice(0, nc - 1); const i = pos ? w.lastIndexOf(d) : 0; items.push({ skill: 'digraph', kind: 'picfill', pic: PIC[w], word: w.slice(0, i) + '__' + w.slice(i + 2), answer: d, choices: shuffle([d, ...others]), say: w }); }
  else if (id === 'sort_ai' || id === 'sort_ee') { const [a, b] = id === 'sort_ai' ? ['ai', 'ay'] : ['ee', 'ea']; const cap = lv <= 3 ? 2 : 3; const la = shuffle(WL[a].filter(x => x.lv <= cap)), lb = shuffle(WL[b].filter(x => x.lv <= cap)); for (let i = 0; items.length < n && i < 12; i++) { if (la[i]) items.push({ skill: 'vowel', kind: 'sort', word: la[i].w, answer: a, choices: [a, b], say: la[i].w }); if (lb[i] && items.length < n) items.push({ skill: 'vowel', kind: 'sort', word: lb[i].w, answer: b, choices: [a, b], say: lb[i].w }); } return shuffle(items); }
  else if (id === 'magic_e') { const pairs = shuffle(MAGIC_E); for (const [a, b] of pairs) { if (items.length >= n) break; const useLong = Math.random() < 0.5; const w = useLong ? b : a; items.push({ skill: 'magic', kind: 'sort', word: w, answer: useLong ? 'magic e' : 'short', choices: ['short', 'magic e'], say: w }); } return items; }
  else if (id === 'fill_vt') { const cap = lv <= 3 ? 2 : 3; const pool = []; for (const t of ['ai', 'ay', 'ee', 'ea']) for (const x of WL[t].filter(x => x.lv <= cap)) pool.push({ w: x.w, clue: x.clue, t }); for (const [w, clue] of OA) pool.push({ w, clue, t: 'oa' });
    for (const x of shuffle(pool)) { if (items.length >= n) break; if (items.some(i => i.say === x.w)) continue; const fam = { ai: ['ai', 'ay', 'oa'], ay: ['ay', 'ai', 'oa'], ee: ['ee', 'ea', 'oa'], ea: ['ea', 'ee', 'oa'], oa: ['oa', 'ai', 'ee'] }[x.t]; const i = x.w.toLowerCase().indexOf(x.t); items.push({ skill: 'vowel', kind: 'fill', word: x.w.slice(0, i) + '__' + x.w.slice(i + 2), clue: x.clue, answer: x.t, choices: shuffle(fam.slice(0, nc)), say: x.w }); } }
  else if (id === 'rctrl') for (const [w, p, clue] of pickN(RCTRL, n)) { const others = ['ar', 'or', 'er', 'ir', 'ur'].filter(x => x !== p && !(['er', 'ir', 'ur'].includes(p) && ['er', 'ir', 'ur'].includes(x))); const i = w.indexOf(p); items.push({ skill: 'rctrl', kind: 'fill', word: w.slice(0, i) + '__' + w.slice(i + 2), clue, answer: p, choices: shuffle([p, ...shuffle(others).slice(0, Math.min(2, nc - 1))]), say: w }); }
  else if (id === 'diph') { const pool = []; for (const t of ['oi', 'oy', 'ou', 'ow']) for (const x of WL[t].filter(x => x.lv <= (lv <= 4 ? 2 : 3))) pool.push({ x, t }); for (const { x, t } of shuffle(pool)) { if (items.length >= n) break; if (items.some(i => i.say === x.w)) continue; const i = x.w.indexOf(t); items.push({ skill: 'diph', kind: 'fill', word: x.w.slice(0, i) + '__' + x.w.slice(i + 2), clue: x.clue, answer: t, choices: shuffle(['oi', 'oy', 'ou', 'ow']), say: x.w }); } }
  else if (id === 'syll') { const ws = [...(SYLL_L[lv] || []), ...(SYLL_L[lv - 1] || [])]; for (const w of shuffle(ws).slice(0, Math.min(7, ws.length))) { const parts = w.split('-'); items.push({ skill: 'syll', kind: 'syll', parts, answer: parts.join(''), say: parts.join('') }); } }
  else if (id === 'sight') { const ti = w => { const i = TRICKY_ORDER.indexOf(w.toLowerCase()); return i < 0 ? 99 : i; }; const pool = shuffle(SIGHT.filter(s => s[3] === lv || s[3] === lv - 1)).sort((a, b) => (school && lv <= 2) ? ti(a[1]) - ti(b[1]) : b[3] - a[3]); for (const [s, a, w] of pool.slice(0, n)) items.push({ skill: 'sight', kind: 'sight', sentence: s, answer: a, choices: shuffle([a, ...w.slice(0, nc - 1)]), say: s.replace('___', a) }); }
  else if (id === 'spell') { const pool = shuffle(SPELL.filter(s => s[1] === lv || s[1] === lv - 1)).sort((a, b) => b[1] - a[1]); for (const [w, , clue, wrong] of pool.slice(0, n)) items.push({ skill: 'spell', kind: 'spell', clue, answer: w, choices: shuffle([w, ...wrong.slice(0, nc - 1)]), say: w }); }
  else if (id === 'affix') { const pool = shuffle(AFFIX.filter(s => s[0] === lv || s[0] === lv - 1)).sort((a, b) => b[0] - a[0]); for (const [, q, a, w] of pool.slice(0, n)) items.push({ skill: 'affix', kind: 'mcq', question: q, answer: a, choices: shuffle([a, ...w]), say: a }); }
  else if (id === 'context') { const pool = shuffle(CONTEXT.filter(s => s[0] === lv || s[0] === lv - 1)).sort((a, b) => b[0] - a[0]); for (const [, s, word, a, w] of pool.slice(0, n)) items.push({ skill: 'context', kind: 'mcq', sentence: s, bold: word, question: `What does “${word}” mean in this sentence?`, answer: a, choices: shuffle([a, ...w]), say: a }); }
  else if (id === 'vocab') {
    const here = vocabAt(lv), below = vocabAt(Math.max(0, lv - 1));
    const pool = shuffle(here).slice(0, Math.min(n, here.length));
    for (const v of pool) {
      const sib = here.filter(x => x.w !== v.w);
      if (v.pic) { const ch = shuffle([v, ...shuffle(sib).slice(0, nc - 1)]).map(x => ({ v: x.w, pic: x.pic, label: x.w })); items.push({ skill: 'vocab', kind: 'picchoice', prompt: `Tap the ${v.w}.`, target: v.w, choices: ch, answer: v.w, say: `${v.w}. ${v.def}`, word: v.w, noLabels: lv <= 1 }); }
      else { const ch = shuffle([v.def, ...shuffle(sib).slice(0, 3).map(x => x.def)]); items.push({ skill: 'vocab', kind: 'mcq', word: v.w, question: `What does “${v.w}” mean?`, answer: v.def, choices: ch, say: `${v.w}. ${v.def}`, example: v.ex }); }
    }
    if (lv >= 7) for (const [, w, s, d] of shuffle(SYN.filter(x => x[0] === lv)).slice(0, 3)) items.push({ skill: 'vocab', kind: 'mcq', word: w, question: `Which word means almost the same as “${w}”?`, answer: s, choices: shuffle([s, ...d]), say: `${w}, ${s}` });
    return shuffle(items);
  }
  return items;
}

// Read It Aloud words and sentences by reading level
export const RA_SENTENCES = {
  1: ['I can see.', 'The cat sat.', 'Look at me.', 'God is good.'],
  2: ['God is kind.', 'I can pray.', 'The tree is green.', 'Be brave.'],
  3: ['God keeps His promise.', 'Share your bread.', 'Trust God every day.', 'A true friend is kind.'],
  4: ['The Lord is my shepherd.', 'Be strong and brave.', 'Go and do likewise.', 'God loves a cheerful giver.'],
  5: ['Noah worked patiently on the enormous ark.', 'Kindness is a choice we can make every day.', 'Joseph forgave his brothers and helped his family.'],
  7: ['Integrity means doing what is right when no one is watching.', 'Perseverance helped the team finish a difficult project.', 'Compassion moves us to help people who are struggling.'],
};
export function readAloudList(lv) {
  let words;
  if (lv <= 1) words = CVC; else if (lv === 2) words = [...BLENDS.map(b => b[0]), ...DIGRAPHS.map(d => d[0])];
  else if (lv === 3) words = [...RCTRL.map(r => r[0]), ...OA.map(o => o[0]), ...WL.ai.filter(x => x.lv <= 2).map(x => x.w), ...WL.ee.filter(x => x.lv <= 2).map(x => x.w)];
  else if (lv === 4) words = [...WL.oi, ...WL.oy, ...WL.ou, ...WL.ow].map(x => x.w).concat(SYLL_L[4].map(w => w.replace(/-/g, '')));
  else words = (SYLL_L[lv] || SYLL_L[9]).map(w => w.replace(/-/g, ''));
  const sk = lv >= 7 ? 7 : lv >= 5 ? 5 : Math.max(1, lv);
  return { words: shuffle([...new Set(words)]).slice(0, 8), sentences: RA_SENTENCES[sk] || RA_SENTENCES[4] };
}
// Say It With Me words: [word with syllable hyphens, sounds]
export const SAY_WORDS = [
  ['rain-bow', ['r']], ['red', ['r']], ['rock', ['r']], ['friend', ['r', 'bl']], ['tree', ['r', 'bl']], ['car', ['r']],
  ['lamb', ['l']], ['light', ['l']], ['lion', ['l']], ['bell', ['l']], ['ap-ple', ['l']], ['yel-low', ['l']],
  ['sun', ['s']], ['seed', ['s']], ['sing', ['s']], ['bus', ['s']], ['house', ['s']], ['stone', ['s', 'bl']],
  ['thank-ful', ['th']], ['three', ['th', 'r']], ['thumb', ['th']], ['bath', ['th']], ['broth-er', ['th', 'r', 'bl']], ['feath-er', ['th']],
  ['bread', ['bl', 'r']], ['crown', ['bl', 'r']], ['flag', ['bl', 'l']], ['plant', ['bl', 'l']], ['slide', ['bl', 's', 'l']], ['spoon', ['bl', 's']],
  ['bless-ing', ['bl', 'l', 's']], ['fam-i-ly', ['l']], ['hap-py', []], ['to-geth-er', ['th']], ['gen-tle', ['l']], ['kind-ness', ['s']],
];
